import 'jquery';
import 'swiper';
import 'animejs';
import "gsap/TweenMax";
import 'ScrollMagic';
import 'animation.gsap';
import 'debug.addIndicators';
import 'malihu-custom-scrollbar-plugin';
import 'jquery-mousewheel';
import 'jquery.maskedinput/src/jquery.maskedinput.js';
import 'jquery-validation/dist/jquery.validate.min.js';
import 'jquery-validation/dist/localization/messages_ru.js';
import './vendor/jquery-validation/src/additional/minlengthphone.js';
// import 'jquery.scrollbar';
import './vendor/svg/svg-sprite.js';
